#ifndef __ADC_DEFINES_H__
#define __ADC_DEFINES_H__

#define U15V_CHANNEL			ADC_CHSELR_CHSEL7
#define U15V_CURRENT_CHANNEL	ADC_CHSELR_CHSEL10
#define U12V_CHANNEL			ADC_CHSELR_CHSEL14
#define U12V_CURRENT_CHANNEL	ADC_CHSELR_CHSEL12
#define U24VO2_CHANNEL			ADC_CHSELR_CHSEL5
#define U24VO2_CURRENT_CHANNEL	ADC_CHSELR_CHSEL11
#define U24V_CHANNEL			ADC_CHSELR_CHSEL9
#define U24V_CURRENT_CHANNEL	ADC_CHSELR_CHSEL2
#define U5VK_CHANNEL			ADC_CHSELR_CHSEL15
#define U5VK_CURRENT_CHANNEL	ADC_CHSELR_CHSEL0
#define U5V_CHANNEL				ADC_CHSELR_CHSEL8
#define U5V_CURRENT_CHANNEL		ADC_CHSELR_CHSEL1
#define U_BAT_CHANNEL			ADC_CHSELR_CHSEL6
#define PAD9_CHANNEL			ADC_CHSELR_CHSEL4
#define PAD15_CHANNEL			ADC_CHSELR_CHSEL13
#define U48V_CURRENT_CHANNEL	ADC_CHSELR_CHSEL3

#endif //__ADC_DEFINES_H__
